on: push
name: Push
jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run all checks
      uses: cedrickring/golang-action@1.6.0
      env:
        GO111MODULE: "on"